---
- name: Preconfig
  hosts: cluster
  become: true
  tasks:
    - name: Install Docker
      block:
        - name: Remove old version
          yum:
            name:
              - docker
              - docker-client
              - docker-client-latest
              - docker-common
              - docker-latest
              - docker-latest-logrotate
              - docker-logrotate
              - docker-engine
            state: absent
        - name: Add Docker-CE stable repo
          yum_repository:
            name: docker-ce-stable
            description: Docker CE Stable Repo
            baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
            gpgkey: https://download.docker.com/linux/centos/gpg
            gpgcheck: yes
        - name: Install yum utils
          yum:
            name:
              - yum-utils
              - device-mapper-persistent-data
              - lvm2
            state: present
            # update_cache: yes
        - name: install docker
          yum:
            name: "{{ packages }}"
            update_cache: yes
          vars:
            packages:
              - docker-ce
              - docker-ce-cli
              - containerd.io
        - name: enable docker services
          ansible.builtin.systemd:
            state: started
            name: docker
            enabled: true
      become: true
    - name: docker compose install
      block:
        - name: check compose version
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: install docker compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: "/usr/local/bin/docker-compose"
            mode: 0755
    - name: Завершение установки
      block:
        - name: create group docker
          ansible.builtin.group:
            name: docker
            state: present
        - name: Добавление пользователя в группу  docker
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true
        - name: Reboot server
          reboot:
            reboot_timeout: 3600