---
- name: Preconfig
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      block:
        - name: Install yum utils
          yum:
            name:
              - yum-utils
            state: present
        - name: Remove old version
          yum:
            name:
              - docker
              - docker-client
              - docker-client-latest
              - docker-common
              - docker-latest
              - docker-latest-logrotate
              - docker-logrotate
              - docker-engine
            state: absent
        - name: fix add repo
          shell: sed -i 's/$releasever/7/g' /etc/yum.repos.d/docker-ce.repo
          run_once: true
        - name: add repo for centos 7
          yum_repository:
            name: docker-ce
            description: docker-ce
            baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        - name: install docker
          yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: yes
        - name: enable docker services
          ansible.builtin.systemd:
            state: started
            name: docker
            enabled: yes
      become: yes
    - name: docker compose install
      block:
        - name: check compose version
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: install docker compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: "/usr/local/bin/docker-compose"
            mode: 0755
    - name: Завершение установки
      block:
        - name: create group docker
          ansible.builtin.group:
            name: docker
            state: present
        - name: Добавление пользователя в группу  docker
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes
        - name: Reboot server
          reboot:
            reboot_timeout: 3600

