---
- name: User
  hosts: demo2
  tasks:
    - name: REBOOT
      block:
        - name: Reboot server
          shell: reboot
          async: 1000
          poll: 0
      become: true
    # - name: preconfig block
    #   block:
    #     - name: Sleep
    #       command: /usr/bin/sleep 15
    #       async: 1000
    #       poll: 0
    #       register: sleep
    #     - debug:
    #         var: sleep
    #     - name: Echo
    #       command: echo "DONE"
    #    become: true
    # - name: checkSleep status
    #   async_status:
    #     jid: '{{ sleep.ansible_job_id  }}'
    #   register: job_result
    #   until: job_result.finished
    #   retries: 100
    #   delay: 1
    #   become: true